welcome = ("Welcome to python learning")
author = ("by K3013")
code1 = ("hello world")
challenge = ("Now try to show your own message")
name = input("set your name : ")
input(welcome)+" "+(name)
input(author)
print("According yourself, what will do this code in python ?")
input("print"+" "+str(code1))
print("hello world")
input("'print' will show a message you choosen")
print(challenge)
input()
print("the solution is")
input("print ('your message')")
input("wanna retry ? restart this program")
input("press 'enter' for exit")
